### PR TITLE
Localization features and fixing the issue with Unicode characters in TextAreas.

### LINKED ISSUE #2: Non-inernational
Trying to use a script besides latin (not yet seen any working) will resut in squares,

http://puu.sh/d2wtW/9c619ce340.png

i hope this to be possible in future versions

^^. osswix

### PR DESCRIPTION
**Pull request by cofl**
Added a system by which multiple interface languages may be supported, as well as the ability for users to add their own languages. Also fixed [this issue](https://github.com/DoctorAlpaca/dictionary/issues/2) where Unicode characters in EditEntryWindow's TextAreas wouldn't display properly.

### CODE REVIEW

**Comment by DoctorAlpaca** [comment]
Thanks a lot! However for future contributions it'd be nice to open a feature request and claiming it yourself first, just so I don't start working on the same thing you do.

**Comment by cofl** [comment]
I'll do that.

**Comment by DoctorAlpaca** [comment]
Loading in different languages doesn't seem to work properly; I added a second language to test it with and only some entries show the translated strings.

**Comment by cofl** [comment]
I checked with your file, it all seems to be working for me. What part seems to be broken?

Edit: Did you only do a few of the strings at a time? The file doesn't doesn't update if it already exists. I'll fix it.

**Comment by DoctorAlpaca** [comment]
local
The status text has the translated "Wilkommen", but nothing else is translated. It also seems to enter panic mode when I launch it from the .jar file, so it might just be a problem with my tools. Currently looking into that.

**Comment by DoctorAlpaca** [comment]
Just saw that you save the translations in the users application data folder, I still had an older version with not all string translated lying around there. Might be a good idea to always load the .lang files directly from the .jar.

**Comment by cofl** [comment]
Got that fixed. I'll add it to my pull request. Edit: done.

**Pull request merged**
